#!/usr/bin/env python3
"""
Cosmic Colony Wiki Index Generator

Generates a comprehensive index of all wiki pages for easy navigation
and LLM agent discovery.

Usage:
    python generate_index.py
"""

import json
import os
from pathlib import Path
from collections import defaultdict


class WikiIndexGenerator:
    def __init__(self, wiki_root="CosmicWiki"):
        self.wiki_root = Path(wiki_root)
        self.pages_dir = self.wiki_root / "pages"
        self.output_file = self.wiki_root / "WIKI_INDEX.md"

    def scan_wiki_pages(self):
        """Scan all wiki pages and extract metadata."""
        pages = []

        for md_file in self.pages_dir.rglob("*.md"):
            metadata = self.extract_metadata(md_file)
            if metadata:
                pages.append(metadata)

        return pages

    def extract_metadata(self, file_path):
        """Extract metadata from a wiki page."""
        try:
            with open(file_path, 'r') as f:
                content = f.read()

            # Extract title (first # heading)
            title = "Unknown"
            for line in content.split('\n'):
                if line.startswith('# '):
                    title = line[2:].strip()
                    break

            # Try to extract JSON data block
            json_data = None
            if '```json' in content:
                json_start = content.find('```json') + 7
                json_end = content.find('```', json_start)
                json_str = content[json_start:json_end].strip()
                try:
                    json_data = json.loads(json_str)
                except:
                    pass

            # Get category from path
            category = file_path.parent.name

            # Extract ACNH equivalent
            acnh_equivalent = "Unknown"
            if '**ACNH Equivalent:**' in content:
                idx = content.find('**ACNH Equivalent:**')
                line_end = content.find('\n', idx)
                acnh_line = content[idx:line_end]
                # Extract from markdown link if present
                if '[' in acnh_line and ']' in acnh_line:
                    start = acnh_line.find('[') + 1
                    end = acnh_line.find(']')
                    acnh_equivalent = acnh_line[start:end]

            metadata = {
                'title': title,
                'file_path': str(file_path.relative_to(self.wiki_root)),
                'category': category,
                'acnh_equivalent': acnh_equivalent,
                'json_data': json_data
            }

            return metadata

        except Exception as e:
            print(f"Error processing {file_path}: {e}")
            return None

    def generate_index(self):
        """Generate the wiki index markdown file."""
        pages = self.scan_wiki_pages()

        # Group by category
        by_category = defaultdict(list)
        for page in pages:
            by_category[page['category']].append(page)

        # Sort categories
        categories = sorted(by_category.keys())

        # Build index content
        content = self._build_index_content(by_category, categories)

        # Write to file
        with open(self.output_file, 'w') as f:
            f.write(content)

        print(f"✅ Generated wiki index: {self.output_file}")
        print(f"   Total pages: {len(pages)}")
        print(f"   Categories: {len(categories)}")

    def _build_index_content(self, by_category, categories):
        """Build the markdown content for the index."""
        content = """# Cosmic Colony Wiki - Master Index

> **📖 Complete catalog of all wiki pages**
>
> This index is automatically generated. Use it to navigate the wiki or query specific items.

**Last Updated:** {date}

---

## Table of Contents

{toc}

---

## Quick Stats

- **Total Pages:** {total_pages}
- **Categories:** {total_categories}

---

## Pages by Category

{category_sections}

---

## LLM Agent Quick Reference

### Find All Pages
```bash
# List all wiki pages
find CosmicWiki/pages -name "*.md"

# Search by category
ls CosmicWiki/pages/nebula_organisms/

# Search by tag
Grep for "tag-name" in CosmicWiki/pages/**/*.md
```

### Query Patterns
```bash
# Find item by ACNH name
Grep for "ACNH Equivalent.*Sea Bass" in CosmicWiki/pages/**/*.md

# Find items by price range
Grep for '"sell_price_credits": 4' in CosmicWiki/pages/**/*.md

# Find items by rarity
Grep for '"rarity": "Rare"' in CosmicWiki/pages/**/*.md

# Find items using specific TopDown class
Grep for '"primary_class": "PickableItem"' in CosmicWiki/pages/**/*.md
```

---

## ACNH to Cosmic Quick Reference

{acnh_mapping_table}

---

<sub>**Index Metadata:**</sub>
<sub>Auto-generated by `scripts/generate_index.py`</sub>
"""

        from datetime import date

        # Build TOC
        toc = "\n".join([f"- [{cat.replace('_', ' ').title()}](#{cat})" for cat in categories])

        # Build category sections
        category_sections = []
        for category in categories:
            section = f"### {category.replace('_', ' ').title()} {{#{category}}}\n\n"
            section += "| Cosmic Name | ACNH Equivalent | File Path |\n"
            section += "|-------------|-----------------|----------|\n"

            for page in sorted(by_category[category], key=lambda p: p['title']):
                section += f"| **{page['title']}** | {page['acnh_equivalent']} | `{page['file_path']}` |\n"

            category_sections.append(section)

        # Build ACNH mapping table
        acnh_table = "| ACNH Item | Cosmic Equivalent | Category | Link |\n"
        acnh_table += "|-----------|-------------------|----------|------|\n"

        all_pages = []
        for cat_pages in by_category.values():
            all_pages.extend(cat_pages)

        for page in sorted(all_pages, key=lambda p: p['acnh_equivalent']):
            acnh_table += f"| {page['acnh_equivalent']} | {page['title']} | {page['category']} | [{page['title']}]({page['file_path']}) |\n"

        # Fill template
        content = content.format(
            date=str(date.today()),
            toc=toc,
            total_pages=sum(len(pages) for pages in by_category.values()),
            total_categories=len(categories),
            category_sections="\n\n".join(category_sections),
            acnh_mapping_table=acnh_table
        )

        return content


def main():
    generator = WikiIndexGenerator()
    generator.generate_index()


if __name__ == "__main__":
    main()
